/* Task 1.1. Add your movie data here 
   and export it so it's available in server.js */
export const movieModel = {
tt0185906: {
    imdbID: `tt0185906`,
    "Title": "Band of Brothers",
    "Released": "2001-09-09",
    "Runtime": 594,
    "Genres": ["Action", "Drama", "History"],
    "Directors": [],
    "Writers": [],
    "Actors": ["Scott Grimes", "Damian Lewis", "Ron Livingston"],
    "Plot": "The story of Easy Company of the U.S. Army 101st Airborne Division and their mission in World War II Europe, from Operation Overlord to V-J Day.",
    "Poster": "https://m.media-amazon.com/images/M/MV5BMTQ3NTdmOTEtZTRmMi00NTg5LWI5NmUtYTNiOTc0ZmNkODU0XkEyXkFqcGc@._V1_SX300.jpg",
    "Metascore": 0,
    "imdbRating": 9.4,
},
tt0056058: {
    imdbID: `tt0056058`,
    "Title": "Harakiri",
    "Released": "1962-08-04",
    "Runtime": 133,
    "Genres": ["Drama", "Mystery"],
    "Directors": ["Masaki Kobayashi"],
    "Writers": ["Yasuhiko Takiguchi", "Shinobu Hashimoto"],
    "Actors": ["Tatsuya Nakadai", "Akira Ishihama", "Shima Iwashita"],
    "Plot": "When a ronin requesting seppuku at a feudal lord's palace is told of the brutal suicide of another ronin who previously visited, he reveals how their pasts are intertwined - and in doing so challenges the clan's integrity.",
    "Poster": "https://m.media-amazon.com/images/M/MV5BZThiZjU5ZDQtZDI4Mi00ZGYyLTkzOTktYmIzZTFlZTkxYzg5XkEyXkFqcGc@._V1_SX300.jpg",
    "Metascore": 85,
    "imdbRating": 8.6,
},
tt12042730: {
    imdbID: `tt12042730`,
    "Title": "Project Hail Mary",
    "Released": "2026-03-20",
    "Runtime": 156,
    "Genres": ["Drama", "Sci-Fi", "Thriller"],
    "Directors": ["Phil Lord", "Christopher Miller"],
    "Writers": ["Drew Goddard", "Andy Weir"],
    "Actors": ["Ryan Gosling", "Milana Vayntrub", "Ken Leung"],
    "Plot": "Science teacher Ryland Grace wakes up alone on a spaceship light-years from Earth. As his memory returns, he uncovers a mission to stop a mysterious substance killing the sun, and save Earth. An unexpected friendship may be the key.",
    "Poster": "https://m.media-amazon.com/images/M/MV5BNTkwNzJiYTctNzI3NC00NjE1LTlhYjktY2Q5MTdmMWFmNzcxXkEyXkFqcGc@._V1_SX300.jpg",
    "Metascore": 0,
    "imdbRating": 0,
},
}